# Generated by Django 4.2.7 on 2023-11-28 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonAPI', '0002_rename_menuitem_menuitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menuitem',
            new_name='menuitems',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='menuitems',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitems', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitems')},
        ),
    ]
